- name: Download filebeat
  shell: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.4.3-amd64.deb

- name: Install filebeat
  shell: sudo dpkg -i filebeat-6.4.3-amd64.deb

- name: Ensure that elasticsearch is running
  systemd:
    state: started
    name: elasticsearch
