---

# GCP Specific Details
zone: "us-central1-a"
region: "us-central1"
network_tags:
  - http-server
machine_type: f1-micro
expose: false

# For all
bastion_ip_address: 0.0.0.0
datacentre: default
server_name: default-server
server_groups:
  - default
