- name: Add core-site.xml configuration
  template:
    src: ../templates/core-site.xml.j2
    dest: /opt/{{ hadoop_version }}/etc/hadoop/core-site.xml

- name: Add hdfs-site.xml configuration
  template:
    src: ../templates/hdfs-site-master.xml.j2
    dest: /opt/{{ hadoop_version }}/etc/hadoop/hdfs-site.xml

- name: Add mapred-site.xml configuration
  template:
    src: ../templates/mapred-site.xml.j2
    dest: /opt/{{ hadoop_version }}/etc/hadoop/mapred-site.xml

- name: Add yarn-site.xml configuration
  template:
    src: ../templates/yarn-site.xml.j2
    dest: /opt/{{ hadoop_version }}/etc/hadoop/yarn-site.xml

- name: Add workers file
  template:
    src: ../templates/workers.j2
    dest: /opt/{{ hadoop_version }}/etc/hadoop/workers

- name: Check for namenode folder
  stat:
    path: /home/hadoop/hdfs/namenode/current
  register: namenode_folder

- name: Format Hadoop namenode
  environment:
    JAVA_HOME: /usr
  become: yes
  become_user: hadoop
  shell: /opt/{{ hadoop_version }}/bin/hdfs namenode -format
  when: namenode_folder["stat"]["exists"] == false

- name: Start hadoop server
  become: yes
  become_user: hadoop
  shell: /opt/{{ hadoop_version }}/sbin/start-dfs.sh
