- name: Download consul
  shell: curl -L -O https://releases.hashicorp.com/consul/1.3.0/consul_1.3.0_linux_amd64.zip

- name: Move consul
  shell: unzip -p consul_1.3.0_linux_amd64.zip > /opt/consul

- name: Ensuring consul is runnable - check consul version
  shell: consul -v
