- name: Install unzip utility
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - unzip

- name: Check that the consul binary exists
  stat:
    path: /usr/local/bin/consul
  register: consul_bin

- include_tasks: install.yml
  when: consul_bin.stat.exists == false

- name: Ensuring consul is runnable - check consul version
  shell: consul -v
  register: consul_shell_version

- name: Print out consul shell output for to ensure output is right
  debug:
    var: consul_shell_version.stdout_lines

- name: Add the user 'consul'
  user:
    name: consul

- name: Create the consul configuration folder if it doesn't exist
  file:
    path: /etc/consul.d
    state: directory
    mode: "0755"
    owner: consul
    group: consul

- name: Create the consul data folder if it doesn't exist
  file:
    path: /tmp/consul
    state: directory
    mode: "0777"
    owner: consul
    group: consul

- name: Generate a consul systemctl configuration to be run by systemd
  template:
    src: ../templates/consul.service.j2
    dest: /etc/systemd/system/consul.service

- include_tasks: server.yml
  when: consul_server is defined

- include_tasks: agent.yml
  when: consul_member is defined
