- name: Install docker on multiple nodes
  hosts: docker
  become: true

  roles:
    - docker

- name: Install docker and docker compose on multiple nodes
  hosts: docker-compose
  become: true

  roles:
    - docker
    - docker-compose

- name: Install docker swarm master
  hosts: dockerswarm-manager
  become: true

  roles:
    - docker
    - docker-compose
    - docker-swarm-manager

- name: Install docker swarm worker
  hosts: dockerswarm-worker
  become: true

  roles:
    - docker
    - docker-compose
    - docker-swarm-worker

- name: Install R
  hosts: r
  become: true

  roles:
    - r

- name: Install Rstudio server
  hosts: rstudio-server
  become: true

  roles:
    - r
    - rstudio-server

- name: Install consul
  hosts: consul
  become: true

  environment:
    PATH: "{{ ansible_env.PATH }}:/opt"

  roles:
    - consul

- name: Install nats
  hosts: nats
  become: true

  environment:
    PATH: "{{ ansible_env.PATH }}:/opt"

  roles:
    - nats

- name: Install java
  hosts: java
  become: true

  roles:
    - java

- name: Install elasticsearch
  hosts: elasticsearch
  become: true

  roles:
    - java
    - elasticsearch

- name: Install python 3
  hosts: python3
  become: true

  roles:
    - python3
