- name: Install docker on multiple nodes
  hosts: docker
  become: true

  roles:
    - docker

- name: Install docker and docker compose on multiple nodes
  hosts: docker-compose
  become: true

  roles:
    - docker
    - docker-compose

- name: Install docker-swarm
  hosts: dockerswarm
  become: true

  roles:
    - docker
    - docker-compose
    - docker-swarm

- name: Install R
  hosts: r
  become: true

  roles:
    - r

- name: Install Rstudio server
  hosts: rstudio-server
  become: true

  roles:
    - r
    - rstudio-server

- name: Install consul
  hosts: consul
  become: true
  roles:
    - role: consul
      consul_server: true

- name: Install nats
  hosts: nats
  become: true

  environment:
    PATH: "{{ ansible_env.PATH }}:/opt"

  roles:
    - nats

- name: Install java
  hosts: java
  become: true

  roles:
    - java

- name: Install elasticsearch
  hosts: elasticsearch
  become: true
  vars:
    num_es_nodes: "{{ groups['elasticsearch'] | length }}"

  roles:
    - elasticsearch

- name: Install python 3
  hosts: python3
  become: true

  roles:
    - python3

- name: Install etcd
  hosts: etcd
  become: true

  roles:
    - etcd

- name: Install Golang runtime
  hosts: golang
  become: true

  roles:
    - golang

- name: Install Golang stackdriver debugger
  hosts: debugger
  become: true
  become_user: hairizuannoorazman

  roles:
    - stackdriver-debugger

- name: Install monitoring agents
  hosts: monitoring
  become: true

  roles:
    - stackdriver-monitoring

- name: Install logging agents
  hosts: logging
  become: true

  roles:
    - stackdriver-logging

- name: Install zookeeper
  hosts: zookeeper
  become: true

  roles:
    - java
    - zookeeper

- name: Install kafka
  hosts: kafka
  become: true

  roles:
    - java
    - kafka
