---

- hosts: localhost
  tasks:
    - name: Set Datacentre name
      set_fact:
        datacentre: "haha"

- hosts: localhost
  vars:
    datacentre: "{{ datacentre }}"
    server_name: bastion
    server_groups:
      - infra
    machine_type: f1-micro
    cloud_provider: google
  roles:
    - role: infra.bastion

- hosts: localhost
  vars:
    datacentre: "{{ datacentre }}"
    server_name: zzaa
    cloud_provider: google
    server_groups:
      - fw
    machine_type: f1-micro
    network_tags:
      - "{{ datacentre }}-allow-internal"
      - "{{ datacentre }}-allow-http"
    bastion_ip_address: "{{ bastion_ip_address }}"
    service_acct: web-basic
    service_acct_display: Service account for web basic application
    scopes: []
  roles:
    - role: infra.compute-add

- hosts: fw
  become: true
  roles:
    # - role: nginx
    - role: app.web-basic
