---

# Following playbook to be deprecated
# We will move provisioning step to utilize terraform instead

- hosts: localhost
  tasks:
    - name: Set Datacentre name
      set_fact:
        datacentre: "haha"

- hosts: localhost
  vars:
    datacentre: "{{ datacentre }}"
    server_name: bastion
    server_groups:
      - infra
    machine_type: e2-micro
    cloud_provider: google
    expose: yes
  roles:
    - role: infra.bastion

# - hosts: localhost
#   vars:
#     datacentre: "{{ datacentre }}"
#     server_name: zzaa
#     cloud_provider: google
#     server_groups:
#       - fw
#     machine_type: e2-micro
#     network_tags:
#       - "{{ datacentre }}-allow-internal"
#       - "{{ datacentre }}-allow-http"
#     bastion_ip_address: "{{ bastion_ip_address }}"
#     service_acct: web-basic
#     service_acct_display: Service account for web basic application
#     expose: yes
#     scopes: []
#   roles:
#     - role: infra.compute-add

# - hosts: fw
#   become: true
#   roles:
#     - role: nginx
#     # - role: app.web-basic

- hosts: localhost
  vars:
    datacentre: "{{ datacentre }}"
    cloud_provider: google
    machine_type: e2-micro
    network_tags: []
    service_acct: etcd-basic
    service_acct_display: Service account for etcd
    expose: no
    scopes: []
  tasks:
    - name: Create etcd nodes
      include_role:
        name: infra.compute-add
      vars:
        server_name: "{{ item }}"
      with_items:
        - etcd-1
        - etcd-2
        - etcd-3

# - hosts: etcd
#   become: true
#   roles:
#     - role: etcd


