- name: apply common configuration to all nodes
  hosts: local
  connection: local

  roles:
    - sample

- name: Testing values across plays
  hosts: local
  connection: local

  roles:
    - sample2
