- name: apply common configuration to all nodes
  hosts: localhost
  connection: local

  # roles:
  #   - sample
  tasks:
    - debug:
        var: hostvars

    - template:
        src: zzz.yml
        dest: zzz0.yml

    - shell: cat "zzz.yml"
      register: miao

    - stat:
        path: ./roles/redis
      register: zzz0_exists

    - debug:
        var: zzz0_exists["stat"]["exists"]
      when: zzz0_exists["stat"]["exists"] == true

    - copy:
        content: "{{ miao.stdout }}"
        dest: "zzz1.yml"
# - name: Testing values across plays
#   hosts: local
#   connection: local

#   roles:
#     - sample2
