- name: Downloading etcd
  shell: curl -L -O https://github.com/etcd-io/etcd/releases/download/v3.3.10/etcd-v3.3.10-linux-amd64.tar.gz

- name: Move binary over to opt folder
  shell: tar xzvf ./etcd-v3.3.10-linux-amd64.tar.gz -C /opt/etcd --strip-components=1

- name: Allow etcd to be executable
  shell: chmod +x /opt/etcd
