- name: Install Rstudio server dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - gdebi-core

- name: Download rstudio binaries
  shell: wget https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.9.923-amd64.deb

- name: Extract and install rstudio server
  shell: sudo gdebi -n shiny-server-1.5.9.923-amd64.deb
