- name: Install python 3 on server
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - python3
      - python3-pip

- name: Install pipenv dependency packages
  pip:
    name:
      - pipenv
      - virtualenv
