- name: Get docker swarm manager ip address
  shell: hostname -i
  register: swarm-manager-ip

- name: Initialize docker swarm
  shell: docker swarm init --advertise-addr {{ swarm-manager-ip.stdout }}

- name: Get docker swarm manager init
  shell: docker swarm join-token -q worker
  register: swarm-manager-token

- name: Get docker workers to join
  shell: docker swarm join --token {{ swarm-manager-token.stdout }}:2377

- name: Get docker node list
  shell: docker node list
  register: docker-node-list

- name: Print out the list of docker nodes available for use
  debug:
    var: docker-node-list
