- name: Pull docker compose files down
  shell: curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  tags:
    - docker-compose

- name: Make the downloaded docker compose file an executable
  shell: chmod +x /usr/local/bin/docker-compose
  tags:
    - docker-compose
