- name: Unarchive prometheus binary
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.5.0/prometheus-2.5.0.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: yes
    mode: +x

- name: Add the user 'prometheus'
  user:
    name: prometheus

- name: Generate a prometheus configuration to be run by systemd
  template:
    src: ../templates/prometheus.yml.j2
    dest: /etc/opt/prometheus/prometheus.yml

- name: Generate a prometheus configuration to be run by systemd
  template:
    src: ../templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
