- name: Import pgp key for elasticsearch
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Install dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - apt-transport-https

- name: Add elasticsearch definitions to repo directory
  shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: Install elasticsearch
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - elasticsearch
