- name: Install ubuntu docker dependencies
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add gpg key to install docker
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Fingerprint step
  shell: apt-key fingerprint 0EBFCD88

- name: Add apt-repository step
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Install docker
  apt:
    name: docker-ce
    update_cache: yes

- name: Add user to docker group
  shell: usermod -aG docker {{ user }}
  when: user is defined
